baseurl                  = "https://vgiles.net"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "vincent giles - composer"
theme                    = "github.com/victoriadrake/hugo-theme-sam"    # pull in theme as hugo module 
# theme                  = "sam"                      # install theme locally (git clone or submodule)
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Copyright 2024 Vincent Giles :: Call me Sam, a theme for Hugo."

# Metadata for Open Graph and Twitter
    description          = "Vincent Giles is an Australian composer based in Naarm (Melbourne) whose music focuses on the boundaries of perception and instability."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "vincent giles - composer"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "https://fcpvg.work"
    text = "blog"

[[params.mainMenu]]
    link = "works"
    text = "works"

[[params.mainMenu]]
    link = "https://faultycat.com.au"
    text = "production"

[[params.mainMenu]]
    link = "about"
    text = "who is vincent?"

[imaging]
    quality = 75
