baseurl                  = "https://vgiles.net"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "vincent giles - composer"
# theme                    = "github.com/victoriadrake/hugo-theme-sam"    # pull in theme as hugo module 
theme                    = "sam"                      # install theme locally (git clone or submodule)
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Copyright 2024 Vincent Giles ::"
    acknowledgement      = "I live and work on stolen Wurundjeri Country in Naarm, Melbourne. As an uninvited guest I acknowledge the great loss caused by colonisation. Sovereignty has never been ceded."

# Metadata for Open Graph and Twitter
    description          = "Vincent Giles is an Australian composer based in Naarm (Melbourne) whose music focuses on the boundaries of perception, instability, and human/machine glitches"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "vincent giles - composer"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/website-test-3.mov"
    type    = "video/mp4"
    poster  = "/hero-draft-transparent-emb.png"
[params.videoBackground]
    # overlay = "rgba(17, 16, 17, 0.8)" # optional
    overlay = "rgb(153, 51, 102, 0.2)"

[[params.mainMenu]]
    link = "about"
    text = "who's vincent?"

[[params.mainMenu]]
    link = "music"
    text = "music"

[[params.mainMenu]]
    link = "https://faultycat.com.au"
    text = "audio production"

[[params.mainMenu]]
    link = "https://fcpvg.work"
    text = "writing"

[[params.mainMenu]]
    link = "https://edition-resonance.xyz"
    text = "publishing"

[[params.mainMenu]]
    link = "contact"
    text = "contact/social"

[imaging]
    quality = 75

[sitemap]
  changeFreq = 'weekly'
  filename = 'sitemap.xml'
  priority = -1