baseURL = "https://vgiles.net/"
languageCode = "en-us"
title = "Vincent Giles"
theme = "minimal"
staticDir = ["static", "static2"]
googleAnalytics = "G-ZMPDSXX8FZ"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Vincent Giles"
    description = "Composer : Performer : Scholar : Producer"
    githubUsername = "vgiles"
    accent = "grey"
    showBorder = true
    backgroundColor = "#f2f2f2"
    font = "Fira Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    featureURL = "https://www.youtube.com/embed/j6LbX4E-EHo"  #copy embed code here -- not working, but the other parts do. To feature you need to insert the iframe embed within index.html
    featureCMP = "Vincent Giles" #composer
    featureTITLE = "when" #title
    featureYEAR = "2021" #year of composition
    copyright = "&copy; 2020 Vincent Giles, all rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)." 

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/statement/"
    name = "Statement"
    weight = 3

[[menu.main]]
    url = "/cds/"
    name = "Releases"
    weight = 4

[[menu.main]]
    url = "/works/"
    name = "Works"
    weight = 5

# [[menu.main]]
#     url = "/research/"
#     name = "Research"
#     weight = 6

[[menu.main]]
    url = "https://faultycat.com.au"
    name = "Production"
    weight = 7

[[menu.main]]
    url = "/curiosity/"
    name = "Curiosities"
    weight = 8

[[menu.main]]
    url = "/pleebland/"
    name = "Pleebland"
    weight = 9

[[menu.main]]
    url = "/calendar/"
    name = "Calendar"
    weight = 10

[[menu.main]]
    url = "https://fcpvg.work"
    name = "Writing"
    weight = 11
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:vin@vgiles.net"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/vgiles/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://soundcloud.com/vince-giles"
    name = "soundcloud"
    weight = 3

[[menu.icon]]
    url = "https://vincentgiles.bandcamp.com"
    name = "bandcamp"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/composervince"
    name = "instagram"
    weight = 5