baseURL = "https://vgiles-net-deployment.onrender.com/"
languageCode = "en-us"
title = "Vincent Giles"
theme = "minimal"

[params]
    author = "Vincent Giles"
    description = "Composer : Performer : Scholar : (site under renovation)"
    githubUsername = "vgiles"
    accent = "grey"
    showBorder = true
    backgroundColor = "#f2f2f2"
    font = "Fira Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/statement/"
    name = "Statement"
    weight = 3

[[menu.main]]
    url = "/cds/"
    name = "CDs"
    weight = 4

[[menu.main]]
    url = "/works/"
    name = "Works"
    weight = 5

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 6

[[menu.main]]
    url = "/teaching/"
    name = "Teaching"
    weight = 7

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:vin@vgiles.net"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/vgiles/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://soundcloud.com/vince-giles"
    name = "soundcloud"
    weight = 3

[[menu.icon]]
    url = "https://vincentgiles.bandcamp.com"
    name = "bandcamp"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/composervince"
    name = "instagram"
    weight = 5